baseURL = "https://mespe.github.io/"
languageCode = "en-us"
title = "Thousand words"
theme = "minos"
paginate = 10
SectionPagesMenu = "main"



[params]
	Author = "Matt Espe"
	smartToc = true
	github = "mespe"
	googleAnalytics = "UA-101069222-1"

[[menu.main]]
	name = "About me"
	url = "/about/"

	