#baseURL = ""
title = "Thousand words..."
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""
Paginate = 5

PygmentsCodeFences = true
pygmentsstyle = "paraiso-dark"

preserveTaxonomyNames = true

[params]
  description = "Thoughts on agriculture, data science, and academia"
  dateFormat = "2006, Jan 2"
  copyrightOwner = "Matt Espe"
  copyrightStartYear = "2017"
  favicon = "favicon.ico"
  hideEntryNavigation = false
  customCSS = ["css/custom.css"]
  customJS = ["js/custom.js"]
  hideSocialMenu = false
  showReadTime = true

[params.seo]
  # Title Separator: - – — · • * ⋆ | ~ « » < >
  titleSeparator = "•"

[params.opengraph]
  [params.opengraph.facebook]
    admins = ""
    appid = ""

[taxonomies]
  category = "categories"
  tag = "tags"

[social]
  facebook = "bob"

[author]
  name = "Matt Espe"

[author.social]
#  codepen = "bob"
  email = "mespe@ucdavis.edu"
#  facebook = "bob"
  github = "mespe"
#  instagram = "bob"
  twitter = "mespe"

[permalinks]
  page = "/:slug/"


[[menu.main]]
	name = "Blog"
	url = "/post/"
	weight = 1
	
[[menu.main]]
	name = "About me"
	url = "/about/"
	weight = 2
	
[[menu.main]]
	name = "Research"
	url = "/research/"
	weight = 3

[[menu.main]]
	name = "Repos"
	weight = 4
	identifier = "repository"
	url = "https://github.com/mespe"

[[menu.main]]
	name = "CV"
	weight = 5
	url = "/docs/espe_cv.pdf"
	
# Language Configuration
defaultContentLanguage = "en"

[languages]
  # edit this block for your own language
  [languages.en]
    lang = "en"
    languageName = "English"
    weight = 1
